### ISSUE TITLE
[Hypertopic] Journal de bord

### ISSUE THREAD

**Issue by christophe-lejeune** [Hypertopic/Protocol#2]
L'ensemble de la platerforme Hypertopic poursuit, entre autres buts, de documenter le travail d'analyse des chercheurs en sciences humaines. Il s'agit d'être en mesure de montrer les documents étudiés ainsi que la façon dont ils sont "annotés" par différents chercheurs. L'idée de "traçabilité" d'une recherche en cours est difficilement séparable du cahier de laboratoire ou du journal de bord. Selon moi, le "carnet de bord" fait donc partie de notre programme de recherche. Un tel journal pourrait bien entendu être "généré" à partir des "log" de nos applications. Mais il ne devrait pas se limiter à ces traces formelles d'activité et fournir un espace d'écriture aux chercheurs. Cet espace permettrait de consigner à la fois la raison d'être des "annotations", les lectures (théoriques) qui les ont inspirées, les différentes pistes suivies, les raisons pour lesquelles une de ces pistes est infléchie (voire abandonnée), etc. 
Que faire d'une telle idée ? 
Est-elle reconnue comme utile par plusieurs d'entre nous ? 
S'agira-t-il de développer un nouvel outil ? De l'intégrer à un outil existant ?

**Comment by benel** [comment]
Je te recommande la version 3 de Cassandre ;)
